<a href="https://colab.research.google.com/github/nirjhor123/NumPy/blob/master/NumPy_DataTypes_and_Attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#numpy's datatype
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [9]:
a1.shape

(3,)

In [3]:
#checking type
type(a1)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3.3],[4,5,6.5]])
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
             [13,14,15],
             [16,17,18]]
            ])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a2.shape

(2, 3)

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [13]:
a1.dtype

dtype('int64')

In [14]:
a2.dtype

dtype('float64')

In [15]:
a3.dtype

dtype('int64')

In [16]:
#elements how many elements there
a1.size,a2.size,a3.size

(3, 6, 18)

In [19]:
#create a Dataframe from NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5